spring.application.name=geisha

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/geishaDB
spring.datasource.username=postgres
spring.datasource.password=2010

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect