spring.application.name=geisha

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:geishaDB}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:2010}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect